### ISSUE TITLE
It raised exception when using ai2thor-docker

### ISSUE THREAD

**Issue by FQYQC** [allenai/ai2thor#1025]
I build the ai2thor-docker following `README` in [ai2thor-docker](https://github.com/allenai/ai2thor-docker), when I run `run.sh`, it raised the following exception:
```
Traceback (most recent call last):
  File "example_agent.py", line 7, in <module>
    controller = ai2thor.controller.Controller(platform=ai2thor.platform.CloudRendering, scene='FloorPlan28')
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 498, in __init__
    host=host,
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 1295, in start
    self._start_unity_thread(env, width, height, unity_params, image_name)
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 1019, in _start_unity_thread
    raise Exception(message)
Exception: Unity process has exited - check Player.log for errors. Confirm that Vulkan is properly configured on this system using vulkaninfo from the vulkan-utils package. returncode=-11
```

I tried to install vulkan-utils in the docker container and run `python3 example_agent.py` manually, but it didn't work.

Environment infomation:
OS: Ubuntu 20.04.4 LTS
GPU：RTX 3090, cuda 11.6

**Comment by FQYQC** [comment]
the Player.log:
```
Mono path[0] = '/root/.ai2thor/releases/thor-CloudRendering-22d62af5da45708e7bc40bf07a861e7397f9d2f9/thor-CloudRendering-22d62af5da45708e7bc40bf07a861e7397f9d2f9_Data/Managed'
Mono config path = '/root/.ai2thor/releases/thor-CloudRendering-22d62af5da45708e7bc40bf07a861e7397f9d2f9/thor-CloudRendering-22d62af5da45708e7bc40bf07a861e7397f9d2f9_Data/MonoBleedingEdge/etc'
Preloaded 'libjpeg.so'
Preloaded 'libpngslz.so'
Preloaded 'libturbojpeg.so'
Loading player data from /root/.ai2thor/releases/thor-CloudRendering-22d62af5da45708e7bc40bf07a861e7397f9d2f9/thor-CloudRendering-22d62af5da45708e7bc40bf07a861e7397f9d2f9_Data/data.unity3d
Unable to load player prefs
Initialize engine version: 2020.3.25f1 (d6f108e0625e)
[Subsystems] Discovering subsystems at path /root/.ai2thor/releases/thor-CloudRendering-22d62af5da45708e7bc40bf07a861e7397f9d2f9/thor-CloudRendering-22d62af5da45708e7bc40bf07a861e7397f9d2f9_Data/UnitySubsystems
Forcing GfxDevice: Vulkan
GfxDevice: creating device client; threaded=1
[Vulkan init] extensions: count=2
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
[Vulkan init] SelectPhysicalDevice requestedDeviceIndex=-1 xrDevice=(nil)
Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
```

**Comment by LenaMnz** [comment]
I met the same error. Did you solve it?
