### ISSUE TITLE
ai2thor 2.1.0 version stuck when calling step()

### ISSUE THREAD

**Issue by deemolover** [allenai/ai2thor#1105]
I've trying to get the 2.1.0 version work because it's the only version supported by the dataset I'm using. For example when running this snippets from the 2.1.0 documentation:

```
import ai2thor.controller
controller = ai2thor.controller.Controller()
controller.start()
controller.reset('FloorPlan28')
controller.step(dict(action='Initialize', gridSize=0.25))
```

The first 4 lines looks fine but any following step() call would get the process stuck. Ctrl+C Interruption gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<some_path>/miniconda3/envs/alfred/lib/python3.8/site-packages/ai2thor/controller.py", line 654, in step
    self.last_event = queue_get(self.request_queue)
  File "/<some_path>/miniconda3/envs/alfred/lib/python3.8/site-packages/ai2thor/server.py", line 41, in queue_get
    res = que.get(block=True, timeout=0.5)
  File "/<some_path>/miniconda3/envs/alfred/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/<some_path>/miniconda3/envs/alfred/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
```

No Player.log found in the log directory. The latest version can take steps normally. Any idea on how to fix or debug this issue?

**Comment by deemolover** [comment]
A re-installation of my environment solved the issue, though I knew nothing about the cause.
