### ISSUE TITLE
The support for multi-agent in ProcTHOR-10k.

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/ai2thor#1169]
Can the scene in procthor-10k support multi-agent setting?
When we load the ai2thor scene, and use agentCount=2 to initize two agents, we can get the following event results of `c.last_event.events`:
```
[<ai2thor.server.Event at 0x7fd536313850
    .metadata["lastAction"] = Initialize
    .metadata["lastActionSuccess"] = True
    .metadata["errorMessage"] = "
    .metadata["actionReturn"] = {'cameraNearPlane': 0.009999999776482582, 'cameraFarPlane': 20.0}
>, <ai2thor.server.Event at 0x7fd536313760
    .metadata["lastAction"] = Initialize
    .metadata["lastActionSuccess"] = True
    .metadata["errorMessage"] = "
    .metadata["actionReturn"] = {'cameraNearPlane': 0.009999999776482582, 'cameraFarPlane': 20.0}
>]
```
But when we load the procthor-10k scene, and use agentCount=2 to initize two agents, we can only get the following event results of `c.last_event.events`:
```
[<ai2thor.server.Event at 0x7fd5351e87c0
    .metadata["lastAction"] = CreateHouse
    .metadata["lastActionSuccess"] = True
    .metadata["errorMessage"] = "
    .metadata["actionReturn"] = None
>]
```
We use the controller by
```
house=dataset["train"][0]
c = Controller(scene=house, agentCount=2)
```
And when we try to make the agent of agentId=1 to execute the specific action by e2 = c.step("RotateRight", agentId=1), it would get this error:
```
Traceback (most recent call last):
  File "../lib/python3.9/site-packages/ai2thor/controller.py", line 979, in step
    self.last_event = self.server.receive()
  File "../lib/python3.9/site-packages/ai2thor/fifo_server.py", line 229, in receive
    metadata, files = self._recv_message(
  File "../lib/python3.9/site-packages/ai2thor/fifo_server.py", line 145, in _recv_message
    header = self._read_with_timeout(
  File "../python3.9/site-packages/ai2thor/fifo_server.py", line 134, in _read_with_timeout
    raise TimeoutError(f"Reading from AI2-THOR backend timed out (using {time
```
So how to use the multi-agent setting in the scene of Procthor-10k?

**Comment by winthos** [comment]
We don't officially support multi-agent functionality in ProcTHOR scenes. We hope to support this in future version releases.

**Comment by abpaudel** [comment]
Hi, it seems like it has been a while and I wanted to check in on this issue. Is the multi-agent functionality for ProcTHOR scenes still under development or has it not started yet? If it is being developed, can you point me to where it is being developed? If not, can you provide some insights on why it doesn't work for ProcTHOR but works for AI2THOR scenes? (Just found this issue after creating #1265)
