### ISSUE TITLE
How to use CloudRendering

### ISSUE THREAD

**Issue by JACK-Chen-2019** [allenai/ai2thor#1207]
from ai2thor.controller import Controller
from ai2thor.platform import CloudRendering
controller = Controller(platform=CloudRendering)

Traceback (most recent call last):
  File "debug.py", line 3, in <module>
    controller = Controller(platform=CloudRendering)
  File "/opt/conda/lib/python3.8/site-packages/ai2thor/controller.py", line 518, in __init__
    self.start(
  File "/opt/conda/lib/python3.8/site-packages/ai2thor/controller.py", line 1436, in start
    self._start_unity_thread(env, width, height, unity_params, image_name)
  File "/opt/conda/lib/python3.8/site-packages/ai2thor/controller.py", line 1153, in _start_unity_thread
    raise Exception(message)
Exception: Unity process has exited - check ~/.config/unity3d/Allen\ Institute\ for\ Artificial\ Intelligence/AI2-THOR/Player.log for errors. Confirm that Vulkan is properly configured on this system using vulkaninfo from the vulkan-utils package. returncode=-11

**Comment by YeTianJHU** [comment]
I have the same issue.

**Comment by xinshu-li** [comment]
just comment start() function. It has been removed for advanced ai2thor.

**Comment by LarsLiden** [comment]
same issue here

**Comment by LarsLiden** [comment]
> just comment start() function. It has been removed for advanced ai2thor.

Can you explain this in a bit more detail?   The basic call is failing.  There is no call to start()
c = Controller(platform=CloudRendering, width=320, height=320, scene='FloorPlan1', server_timeout=120)
