### ISSUE TITLE
Local build error 

### ISSUE THREAD

**Issue by hcv1027** [allenai/ai2thor#270]
My environment is docker container ubnuntu 16.04, running as root. I've tried two version of unity: `2018.3.0f2` and `2019.1.0f2` (I can't find `2018.3.0f2` version listed in `task.py`). My local build command is `invoke local-build --arch Linux64`. Below is my error message:
```bash
CreateDirectory '' failed:  (current dir: )

(Unity:10865): dbind-WARNING **: 15:11:27.545: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-qf0g2Q8VqN: Connection refused
[0731/151128:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 10, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.6/dist-packages/invoke/program.py", line 363, in run
    self.execute()
  File "/usr/local/lib/python3.6/dist-packages/invoke/program.py", line 532, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.6/dist-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/invoke/tasks.py", line 128, in __call__
    result = self.body(*args, **kwargs)
  File "/root/project/ai2thor/tasks.py", line 233, in local_build
    if _build('unity', arch, "builds", build_name):
  File "/root/project/ai2thor/tasks.py", line 77, in _build
    result_code = subprocess.check_call(command, shell=True, env=full_env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/Unity-2019.1.0f2/Editor/Unity -quit -batchmode -logFile thor-local-Linux64.log -projectpath /root/project/ai2thor/unity -executeMethod Build.Linux64' returned non-zero exit status 1.
```
How can I fix this problem?

**Comment by winthos** [comment]
You should be able to find the correct version of Unity listed on the Unity Download Archive here: https://unity3d.com/get-unity/download/archive

**Comment by ekolve** [comment]
Closing as the issue appears resolved. One easy way to install is to use Unity Hub and select 2018.4.16f1.
