### ISSUE TITLE
Fail to start the controller with X11 forwarding enabled

### ISSUE THREAD

**Issue by shuyanzhou** [allenai/ai2thor#325]
Hi,

I am trying to use the environment in my headless Linux server. I ssh the X server display to my local macOS. The ssh connection works with xclock, xeyes, etc. However, there is an error when trying to initialize a controller.

Here is the debug information from ssh and the ai2thor:
> debug1: client_input_channel_open: ctype x11 rchan 3 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 54958
debug1: x11_connect_display: $DISPLAY is launchd
debug1: channel 1: new [x11]
debug1: confirm x11
debug1: channel 1: FORCE input drain
debug1: channel 1: free: x11, nchannels 2
debug1: client_input_channel_open: ctype x11 rchan 3 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 54960
debug1: x11_connect_display: $DISPLAY is launchd
debug1: channel 1: new [x11]
debug1: confirm x11
debug1: channel 1: FORCE input drain
debug1: client_input_channel_open: ctype x11 rchan 4 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 54962
debug1: x11_connect_display: $DISPLAY is launchd
debug1: channel 2: new [x11]
debug1: confirm x11
debug1: channel 1: free: x11, nchannels 3
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  86
  Current serial number in output stream:  87
debug1: channel 2: FORCE input drain
debug1: channel 2: free: x11, nchannels 2
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/projects/ogma2/users/shuyanzh/miniconda3/envs/alfred/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/projects/ogma2/users/shuyanzh/miniconda3/envs/alfred/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/ogma2/users/shuyanzh/miniconda3/envs/alfred/lib/python3.7/site-packages/ai2thor/controller.py", line 697, in _start_unity_thread
    raise Exception("command: %s exited with %s" % (command, returncode))
raise Exception("command: %s exited with %s" % (command, returncode))
Exception: command: ['/home/shuyanzh/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64', '-screen-fullscreen', '0', '-screen-quality', '7', '-screen-width', '300', '-screen-height', '300'] exited with 1

Thanks!

**Comment by shuyanzhou** [comment]
Hi,
I am able to fix the problem results from X server according to [this](https://unix.stackexchange.com/questions/317954/x-forwarding-with-indirect-rendering-fails-with-newer-clients)
> X Error of failed request: BadValue (integer parameter out of range for operation)
Major opcode of failed request: 149 (GLX)
Minor opcode of failed request: 3 (X_GLXCreateContext)
Value in failed request: 0x0
Serial number of failed request: 86
Current serial number in output stream: 87

However, the error still occurs when start
>debug1: client_input_channel_open: ctype x11 rchan 3 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 57286
debug1: x11_connect_display: $DISPLAY is launchd
debug1: channel 1: new [x11]
debug1: confirm x11
debug1: channel 1: FORCE input drain
debug1: channel 1: free: x11, nchannels 2
debug1: client_input_channel_open: ctype x11 rchan 3 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 57288
debug1: x11_connect_display: $DISPLAY is launchd
debug1: channel 1: new [x11]
debug1: confirm x11
debug1: channel 1: FORCE input drain
debug1: client_input_channel_open: ctype x11 rchan 4 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 57290
debug1: x11_connect_display: $DISPLAY is launchd
debug1: channel 2: new [x11]
debug1: confirm x11
debug1: channel 1: free: x11, nchannels 3
Found path: /home/shuyanzh/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/home/shuyanzh/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/home/shuyanzh/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Display 0 'default': 3360x1058 (primary device).
Logging to /home/shuyanzh/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
debug1: channel 2: FORCE input drain
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/projects/ogma2/users/shuyanzh/miniconda3/envs/alfred/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/projects/ogma2/users/shuyanzh/miniconda3/envs/alfred/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/ogma2/users/shuyanzh/miniconda3/envs/alfred/lib/python3.7/site-packages/ai2thor/controller.py", line 697, in _start_unity_thread
    raise Exception("command: %s exited with %s" % (command, returncode))
Exception: command: ['/home/shuyanzh/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64', '-screen-fullscreen', '0', '-screen-quality', '7', '-screen-width', '300', '-screen-height', '300'] exited with 1

debug1: channel 2: free: x11, nchannels 2

**Comment by GELIELEO** [comment]
Hi, did you solve it  @shuyanzhou

**Comment by shuyanzhou** [comment]
@GELIELEO Hey, I use [this code](https://gist.github.com/roozbehm/7abfaa3db4520da229ac79f38f8994b0) to start X and 
```bash
export DISPLAY=:0
```

In my case, If the xorg has already been launched in the gpus (w/ nvidia-smi), it can work.

**Comment by SgtVincent** [comment]
@shuyanzhou  Thanks for your solution!  It works well for my server. 

Add more details for my case here: 
Since I have the Xorg running with nouveau drivers on my server before I start ai2thor Controller, I meet some interesting bugs caused by multiple running Xorgs and their potential conflicts.  Then I run 
`sudo killall Xorg`  to kill Xorg running with nouveau drivers and rerun [your code](https://gist.github.com/roozbehm/7abfaa3db4520da229ac79f38f8994b0) and it works. 

Although there are still some unknown errors/warnings, I get frame data successfully. Here are the output logs: 

> Preloaded 'ScreenSelector.so'
Display 0 '0': 1024x768 (primary device).
Display 1 '1': 1024x768 (secondary device).
Display 2 '2': 1024x768 (secondary device).
Display 3 '3': 1024x768 (secondary device).
Logging to /home/chenjunting/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
Initialize return: {'cameraNearPlane': 0.1, 'cameraFarPlane': 20.0}

**Comment by Homagn** [comment]
Hello,

I tried running the startx.py code as mentioned in the above posts but then I get this error.
Can anyone please tell me how to fix this:

File "startx.py", line 97, in <module>
    startx(display)
  File "startx.py", line 86, in startx
    subprocess.call(command)
  File "/home/microway/.conda/envs/tf-gpu/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/microway/.conda/envs/tf-gpu/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/microway/.conda/envs/tf-gpu/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xorg': 'Xorg'

**Comment by mengdi-li** [comment]
> @GELIELEO Hey, I use [this code](https://gist.github.com/roozbehm/7abfaa3db4520da229ac79f38f8994b0) to start X and
> 
> ```shell
> export DISPLAY=:0
> ```
> 
> In my case, If the xorg has already been launched in the gpus (w/ nvidia-smi), it can work.

Hi @shuyanzhou, did you use X11 forwarding in this solution? Were you using the AI2-THOR Docker?
Looking forward to your answers!

**Comment by shuyanzhou** [comment]
> > @GELIELEO Hey, I use [this code](https://gist.github.com/roozbehm/7abfaa3db4520da229ac79f38f8994b0) to start X and
> > ```shell
> > export DISPLAY=:0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In my case, If the xorg has already been launched in the gpus (w/ nvidia-smi), it can work.
> 
> Hi @shuyanzhou, did you use X11 forwarding in this solution? Were you using the AI2-THOR Docker?
> Looking forward to your answers!

@mengdi-li, no. I did not use x11 forwarding or the docker. Docker seems to be easier to launch, maybe you can try.

**Comment by mengdi-li** [comment]
@shuyanzhou thanks! 
I can run ai2thor on a headless server now. The following information might be useful for others.
1. X11 forwarding is not used. Xvfb is not used. 
2. The ai2thor docker is not used. 
3. Start an X server using the [startx](https://github.com/allenai/allenact/blob/main/scripts/startx.py) python script provided by allenact, which is almost the same as the script provided by @shuyanzhou:
    ```
    sudo python /PATH/TO/startx.py &
    ```
    The `startx.py` script runs the `Xorg` command to start a new X session. Note that if there are existing X sessions running on the server, you need to modify `startx.py` to start your X session on a free display. You can check what display ports have been occupied by `ls /tmp/.X11-unix/`. 

    If you don't have the `sudo` permission, you can ask the administrator either to run it for you or add the line `allowed_users = anybody` to `/etc/X11/Xwrapper.config`. In the second situation, you need to modify `startx.py` to avoid using the `tempfile` module which needs the `sudo` permission to create a temporary configuration file at `/tmp/`.

4. Use `nvidia-smi` to check if the new X session is started. You should see `/usr/lib/xorg/Xorg` processes running. 
5. Set the environment variable `DISPLAY` with the display number (e.g. `:1`) of your X session `export DISPLAY=:1`.  
6. You should be able to run ai2thor on the headless server!

**Comment by ekolve** [comment]
With the most recent release (3.2.1 of ai2thor), a script is bundled with the installation named `ai2thor-xorg`, which performs the same task as the startx.py script that has been shared around.  The main benefit of using `ai2thor-xorg` is that there is additional error checking to ensure that the Xorg server gets started up without error. If an error occurs, it will get emitted to the console.  As well, Xorg will be daemonized so there is no need use nohup.  You start Xorg by running:

```bash
sudo ai2thor-xorg start
```
and if you want to stop the server, you can run
```bash
sudo ai2thor-xorg stop
```

**Comment by TopCoder2K** [comment]
@Homagn, have you managed to fix 
```
Exception: command: ['/home/microway/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64', '-screen-fullscreen', '0', '-screen-quality', '7', '-screen-width', '300', '-screen-height', '300'] exited with 1
```
?

**Comment by TopCoder2K** [comment]
Thank you for the fast answer, @Homagn!

Sorry, I haven't given any information about my setup. I'm using Alfred's Dockerfile and docker setup: https://github.com/askforalfred/alfred#docker-setup for a local machine with an attached physical display. I looked through your Dockerfile and didn't notice any suspicious differences (except maybe `RUN pip3 install --upgrade pip`). Do you remember which specific step/command helped you?
Also, it seems that I have some issues with openGL as I'm getting [`libGL error`](https://github.com/askforalfred/alfred/issues/111#issuecomment-1099071270). Have you had any similar ones?
