### ISSUE TITLE
multiprocessing.process hangs while executing controller.step or controller.reset

### ISSUE THREAD

**Issue by Alrick11** [allenai/ai2thor#334]
I am trying to implement A3C, and while using python multiprocessing library, the process hangs while executing controller.step or controller.reset. I also wrote a sample code where I faced the same problem,

Code:
```
import ai2thor.controller
import multiprocessing as mp

def my_fn(event, controller, scene_name):
    print ('Entered function')
    event=controller.step(dict(action='MoveAhead'))
    print ('Action done')
    event=controller.reset(scene_name)    
    return event, controller
    
if __name__=='__main__':
    num_processes=2
    
    controllers=[]
    events=[]
    
    try:
        for i in range(num_processes):
            controllers.append(ai2thor.controller.Controller(scene='FloorPlan1', gridSize=0.25))
            events.append(controllers[i].step(action='MoveAhead'))
        
        processes=[]
        
        for rank in range(num_processes):
            p=mp.Process(name='test', target=my_fn, args=(events[rank], controllers[rank], 'FloorPlan20'))
            p.start()
            processes.append(p)
            
        for p in processes:
            p.join()
            
    finally:
        for c in controllers:
            c.stop()
```

Console output after forcefully exiting the script:

`runfile('/home/alrick/alfred/scripts/MP_controllerReset.py', wdir='/home/alrick/alfred/scripts')
Found path: /home/alrick/.ai2thor/releases/thor-202001071627-Linux64/thor-202001071627-Linux64
Mono path[0] = '/home/alrick/.ai2thor/releases/thor-202001071627-Linux64/thor-202001071627-Linux64_Data/Managed'
Mono config path = '/home/alrick/.ai2thor/releases/thor-202001071627-Linux64/thor-202001071627-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Display 0 '0': 1366x768 (primary device).
Logging to /home/alrick/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
Found path: /home/alrick/.ai2thor/releases/thor-202001071627-Linux64/thor-202001071627-Linux64
Mono path[0] = '/home/alrick/.ai2thor/releases/thor-202001071627-Linux64/thor-202001071627-Linux64_Data/Managed'
Mono config path = '/home/alrick/.ai2thor/releases/thor-202001071627-Linux64/thor-202001071627-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Display 0 '0': 1366x768 (primary device).
Logging to /home/alrick/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
Entered function
Entered function
Process test:
Process test:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alrick/alfred/scripts/MP_controllerReset.py", line 15, in my_fn
    event=controller.step(dict(action='MoveAhead'))
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alrick/alfred/scripts/MP_controllerReset.py", line 15, in my_fn
    event=controller.step(dict(action='MoveAhead'))
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/site-packages/ai2thor/controller.py", line 739, in step
    self.last_event = queue_get(self.request_queue)
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/site-packages/ai2thor/controller.py", line 739, in step
    self.last_event = queue_get(self.request_queue)
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/site-packages/ai2thor/server.py", line 41, in queue_get
    res = que.get(block=True, timeout=0.5)
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/site-packages/ai2thor/server.py", line 41, in queue_get
    res = que.get(block=True, timeout=0.5)
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
KeyboardInterrupt
Exception in thread Thread-65:
Traceback (most recent call last):
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/site-packages/ai2thor/controller.py", line 782, in _start_unity_thread
    raise Exception("command: %s exited with %s" % (command, returncode))
Exception: command: ['/home/alrick/.ai2thor/releases/thor-202001071627-Linux64/thor-202001071627-Linux64', '-screen-fullscreen', '0', '-screen-quality', '7', '-screen-width', '300', '-screen-height', '300'] exited with -11

Traceback (most recent call last):

  File "/home/alrick/alfred/scripts/MP_controllerReset.py", line 40, in <module>
    p.join()

  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)

  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)

  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)

KeyboardInterrupt

Exception in thread Thread-57:
Traceback (most recent call last):
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alrick/anaconda3/envs/alfred/lib/python3.6/site-packages/ai2thor/controller.py", line 782, in _start_unity_thread
    raise Exception("command: %s exited with %s" % (command, returncode))
Exception: command: ['/home/alrick/.ai2thor/releases/thor-202001071627-Linux64/thor-202001071627-Linux64', '-screen-fullscreen', '0', '-screen-quality', '7', '-screen-width', '300', '-screen-height', '300'] exited with -11`

As you can see, print ('Action done'), doesn't get implemented.

Thanks in advance

**Comment by ekolve** [comment]
Sorry for the late response.  You should defer constructing the controller until you are in the child process.  The API has changed a bit - I believe the other issue you may be running in to is that start() is not called on the controller.  To fix your code, you can do something like the following:

```python

controller = None
def my_fn(event,  scene_name):
    global controller
    if controller is None:
        ai2thor.controller.Controller(gridSize=0.25)

    print ('Entered function')
    event=controller.step(dict(action='MoveAhead'))
    print ('Action done')
    event=controller.reset(scene_name)    
    return event, controller
```
And remove all the code that constructs the controllers and passes them to the processes.

**Comment by ekolve** [comment]
Closing - issues appears to be resolved.
