### ISSUE TITLE
controller was stuck for "No handlers could be found for logger "werkzeug" "

### ISSUE THREAD

**Issue by ElizabethDuo** [allenai/ai2thor#54]
I am using thor in multiprocessing.
When reset and initialization were done, it was about to step, the controller was stuck and read 

> No handlers could be found for logger "werkzeug"

When press ctrl+C, it showed info below

> Traceback (most recent call last):
  File "/home/elizabeth/ai2thor.py", line 90, in forward_action
    controller.step(dict(action='MoveAhead', moveMagnitude=move_mag, snapToGrid=False))
  File "/usr/local/lib/python2.7/dist-packages/ai2thor/controller.py", line 537, in step
    self.last_event = queue_get(self.request_queue)
  File "/usr/local/lib/python2.7/dist-packages/ai2thor/server.py", line 39, in queue_get
    res = que.get(block=True, timeout=0.5)
  File "/usr/lib/python2.7/Queue.py", line 177, in get
    self.last_event = queue_get(self.request_queue)
  File "/usr/local/lib/python2.7/dist-packages/ai2thor/server.py", line 39, in queue_get
    self.not_empty.wait(remaining)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    res = que.get(block=True, timeout=0.5)
  File "/usr/lib/python2.7/Queue.py", line 177, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt

How to solve this? Many thanks!!

**Comment by ekolve** [comment]
Could you post a snippet that causes the error?

**Comment by ElizabethDuo** [comment]
It was because of wrongly used variable as numpy array. Thanks Eric for helped!!
