### ISSUE TITLE
My program stuck in fifo_server.py file

### ISSUE THREAD

**Issue by 15800436469try** [allenai/ai2thor#543]
Hi, I have a question, I changed the source code of ai2thor, and built it successfully in macos.  But when I run the code:
```python
import ai2thor.controller
controller=ai2thor.controller.Controller(local_executable_path='/Users/builds/...')

```
my code stuck in the second code,  and I found it stuck  in  fifo_server.py:
```
metadata, files = self._recv_message()
self.server_pipe =open(self.server_pipe_path,"rb")

```
How can I solve this problem?

**Comment by ekolve** [comment]
Can you check the Player.log to see if an error was thrown in Unity?

**Comment by 15800436469try** [comment]
where can I find the Player.log?

**Comment by ekolve** [comment]
If the server_class doesn't fix it, the Player.log can be found in ~/Library/Logs/Allen Institute.../Ai2Thor/Player.log

**Comment by 15800436469try** [comment]
I tried the server_class,It seems to stuck too. and this is my player.log
```
Mono path[0] = '/Users/album/Desktop/ai2thor-master/unity/builds/thor-OSXIntel64-local/thor-OSXIntel64-local.app/Contents/Resources/Data/Managed'
Mono config path = '/Users/album/Desktop/ai2thor-master/unity/builds/thor-OSXIntel64-local/thor-OSXIntel64-local.app/Contents/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.2f1 (20b4642a3455)
[Subsystems] Discovering subsystems at path /Users/album/Desktop/ai2thor-master/unity/builds/thor-OSXIntel64-local/thor-OSXIntel64-local.app/Contents/Resources/Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
2020-12-09 23:41:15.077 AI2-Thor[19368:475109] Color LCD preferred device: Intel Iris Pro Graphics (low power)
2020-12-09 23:41:15.077 AI2-Thor[19368:475109] Metal devices available: 1
2020-12-09 23:41:15.077 AI2-Thor[19368:475109] 0: Intel Iris Pro Graphics (low power)
2020-12-09 23:41:15.077 AI2-Thor[19368:475109] Using device Intel Iris Pro Graphics (low power)
Initializing Metal device caps: Intel Iris Pro Graphics
Begin MonoManager ReloadAssembly
- Completed reload, in  0.084 seconds
Couldn't create a Convex Mesh from source mesh "bowl_volume_10" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
(Filename:  Line: 91)

Couldn't create a Convex Mesh from source mesh "pot_volume_10" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
(Filename:  Line: 91)

UnloadTime: 1.086754 ms

```

**Comment by 15800436469try** [comment]
This is information after adding  server_class,and I found even I did not modify source code,just invoke local-build, it built successfully,but when run the code above,It still stucked in fifo_server.py.
```
Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    controller=ai2thor.controller.Controller(server_class=ai2thor.wsgi_server.WsgiServer,local_executable_path='/Users/album/Desktop/ai2thor-master/unity/builds/thor-OSXIntel64-local/thor-OSXIntel64-local.app/Contents/MacOS/AI2-Thor')
  File "/Users/album/Desktop/ai2thor-master/ai2thor/controller.py", line 428, in __init__
    host=host
  File "/Users/album/Desktop/ai2thor-master/ai2thor/controller.py", line 853, in start
    self.last_event = self.server.receive()
  File "/Users/album/Desktop/ai2thor-master/ai2thor/wsgi_server.py", line 212, in receive
    return queue_get(self.request_queue, self.unity_proc)
  File "/Users/album/Desktop/ai2thor-master/ai2thor/wsgi_server.py", line 39, in queue_get
    res = que.get(block=True, timeout=0.5)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

```

**Comment by 15800436469try** [comment]
This is new player.log
```
NullReferenceException: Object reference not set to an instance of an object
  at System.Text.StringBuilder.Append (System.Char value) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0
  at System.IO.StringWriter.Write (System.Char value) [0x0000d] in <fb001e01371b4adca20013e0ac763896>:0
  at Newtonsoft.Json.JsonTextWriter.WriteEnd (Newtonsoft.Json.JsonToken token) [0x00017] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonWriter.AutoCompleteClose (Newtonsoft.Json.JsonContainerType type) [0x00049] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonWriter.InternalWriteEnd (Newtonsoft.Json.JsonContainerType container) [0x00000] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonWriter.WriteEndObject () [0x00000] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonWriter.WriteEnd (Newtonsoft.Json.JsonContainerType type) [0x00016] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonWriter.WriteEnd () [0x00007] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonWriter.AutoCompleteAll () [0x00002] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonWriter.Close () [0x00008] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonTextWriter.Close () [0x00000] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonWriter.Dispose (System.Boolean disposing) [0x00010] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose () [0x00000] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00036] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.Formatting formatting, Newtonsoft.Json.JsonSerializerSettings settings) [0x0000e] in <394015232cf841bc8e43c6c98d8e6545>:0
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, Newtonsoft.Json.Formatting formatting, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <394015232cf841bc8e43c6c98d8e6545>:0
  at AgentManager.serializeMetadataJson (MultiAgentMetadata multiMeta) [0x0001b] in <965e65881f8b478a8ec69b6657ffbfc7>:0
  at AgentManager+<EmitFrame>d__67.MoveNext () [0x00149] in <965e65881f8b478a8ec69b6657ffbfc7>:0
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <06c1715baaf44bbbaaee3a683e6f2100>:0

(Filename: <fb001e01371b4adca20013e0ac763896> Line: 0)

Curl error 35: Handshake did not perform verification. UnityTls error code: 7

```

**Comment by ruinianxu** [comment]
@15800436469try 
Hi,

I meet the same problem right now. Could you please let me know how you solved this problem?

Thanks
