### ISSUE TITLE
`SetObjectPoses` Hangs with Unity Crash Past Certain `objectPoses` Arg Size

### ISSUE THREAD

**Issue by thomason-jesse** [allenai/ai2thor#591]
I found a disruptive bug in `SetObjectPoses`. Past a certain list size of `objectPoses` object data, the `step` function hangs indefinitely. Keyboard interrupt gives this stack trace

```
Traceback (most recent call last):
...
  File "venv/lib/python3.8/site-packages/ai2thor/controller.py", line 696, in step
    self.last_event = self.server.receive()
  File "venv/lib/python3.8/site-packages/ai2thor/fifo_server.py", line 159, in receive
    metadata, files = self._recv_message()
  File "venv/lib/python3.8/site-packages/ai2thor/fifo_server.py", line 100, in _recv_message
    header = self.server_pipe.read(self.header_size) # message type + length
KeyboardInterrupt
```

With the following error at the bottom of the AI2-Thor Player log

```
Exception: Invalid field type for Client: 45
  at FifoServer.Client.ReceiveMessage () [0x00095] in <bf154667993e475ea4336973a440db6b>:0
  at AgentManager+<EmitFrame>d__75.MoveNext () [0x00443] in <bf154667993e475ea4336973a440db6b>:0
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <06c1715baaf44bbbaaee3a683e6f2100>:0

(Filename: <bf154667993e475ea4336973a440db6b> Line: 0)
```

To test the size of `objectPoses` required to freeze the simulator, I did the following:
1) Load a big list of objectPoses data from file; set N=1
2) Restart the simulator
3) Call `SetObjectPoses` with `objectPoses` list a random subset of the loaded objectPoses of size N
4) Increment N; Goto (2)

The following are the sizes of the `SetObjectPoses` action string itself (e.g., number of characters) needed to freeze the simulator in eight runs of the above:
8207, 8272, 8212, 8377, 8361, 8189, 8250, 8260

The following are the number of object items in the `objectPoses` lists for those 8 runs:
44, 45, 44, 45, 45, 44, 45, 45

So, at around 8200 characters, 44-45 objects' worth of data, the `SetObjectPoses` call seems to overwhelm the Unity fifo server.

Notably, the Unity error is affected by the number of objects in the `objectPoses` list. For hang-ups with a size of 44, the error becomes
```
Exception: Invalid field type for Client: 44
  at FifoServer.Client.ReceiveMessage () [0x00095] in <bf154667993e475ea4336973a440db6b>:0
  at AgentManager+<EmitFrame>d__75.MoveNext () [0x00443] in <bf154667993e475ea4336973a440db6b>:0
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <06c1715baaf44bbbaaee3a683e6f2100>:0

(Filename: <bf154667993e475ea4336973a440db6b> Line: 0)
```

That is, `Invalid field type for Client: ` reports the length of the list when the hangup happens.

Any idea what's going on here or if it can be fixed quickly?

**Comment by ekolve** [comment]
d3520b7fcb9fa331b2fcb2589d710ac0b2bfb8c8 fixes this.
