### ISSUE TITLE
RuntimeError: agentMode must be set to 'default' or 'bot' or 'drone'

### ISSUE THREAD

**Issue by zkytony** [allenai/ai2thor#624]
I just upgraded my ai2thor to 2.7.2 and copy and pasted the first example in the documentation for RoboThor:
```python
from ai2thor.controller import Controller

controller = Controller(
    agentMode="locobot"
    visibilityDistance=1.5,
    scene="FloorPlan_Train3_2",

    # step sizes
    gridSize=0.25,
    movementGaussianSigma=0.005,
    rotateStepDegrees=90,
    rotateGaussianSigma=0.5

    # image modalities
    renderDepthImage=False,
    renderInstanceSegmentation=False,

    # camera properties
    width=300,
    height=300,
    fieldOfView=60
)
```
There are some missing commas.

Also, when I run this code I get 
```
Traceback (most recent call last):
  File "tutorial.py", line 24, in <module>
    fieldOfView=60
  File "/home/kaiyuzh/pyenv/py37/lib/python3.7/site-packages/ai2thor/controller.py", line 514, in __init__
    event = self.reset(scene)
  File "/home/kaiyuzh/pyenv/py37/lib/python3.7/site-packages/ai2thor/controller.py", line 641, in reset
    **self.initialization_parameters
  File "/home/kaiyuzh/pyenv/py37/lib/python3.7/site-packages/ai2thor/controller.py", line 874, in step
    self.last_event.metadata.get("errorMessage", f"{action} failed.")
RuntimeError: agentMode must be set to 'default' or 'bot' or 'drone'
```
Is the documentation correct?

**Comment by zkytony** [comment]
When I set the agentMode to `bot` I get a warning:

```
UserWarning: You are using a RoboTHOR scene without using the standard LoCoBot.
```

**Comment by ekolve** [comment]
Please use agentMode='bot' for 2.72, we will be releasing 2.7.3 which will be compatible with setting agentMode='locobot'.

**Comment by zkytony** [comment]
OK, thanks!
