### ISSUE TITLE
"check_thor.py" of the ALFRED repository incurs the FileExistsError from os.mkfifo.

### ISSUE THREAD

**Issue by maguro27** [allenai/ai2thor#807]
I met the FileExistsError from os.mkfifo when I ran the [`check_thor.py` of the ALFRED repository](https://github.com/askforalfred/alfred/blob/master/scripts/check_thor.py) after running the docker container based on a slightly modified Dockerfile.
The main modification of the Dockerfile is that I change the docker image from nvidia/cuda:$CUDA_VERSION-devel-ubuntu18.04 to nvcr.io/nvidia/cudagl:11.1.1-devel-ubuntu18.04 because my GPU machine does not match the NVIDIA driver version (namely, use cuda 11.1 because of using NVIDIA RTX A6000)
The full error message is as follows,

```
(alfred_env) maguro@s184:~/alfred$ python check_thor.py 
/home/maguro/alfred_env/lib/python3.6/site-packages/ai2thor/controller.py:1198: UserWarning: start method depreciated. The server started when the Controller was initialized.
  "start method depreciated. The server started when the Controller was initialized."
Traceback (most recent call last):
  File "check_thor.py", line 4, in <module>
    c.start()
  File "/home/maguro/alfred_env/lib/python3.6/site-packages/ai2thor/controller.py", line 1209, in start
    self.server.start()
  File "/home/maguro/alfred_env/lib/python3.6/site-packages/ai2thor/fifo_server.py", line 202, in start
    os.mkfifo(self.server_pipe_path)
FileExistsError: [Errno 17] File exists
```

However, I did not meet any error when I ran [the ai2thor minimal example](https://github.com/allenai/ai2thor) and [the exmaple_agent.py of the ai2thor-docker](https://github.com/allenai/ai2thor-docker/blob/main/example_agent.py).

**the ai2thor minimal example**
```
(alfred_env) maguro@s184:~/projects/ai2thor-docker$ python
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ai2thor.controller import Controller
>>> controller = Controller(scene="FloorPlan10")

>>> event = controller.step(action="RotateRight")
>>> metadata = event.metadata
>>> print(event, event.metadata.keys())
<ai2thor.server.Event at 0x7fca1f41f208
    .metadata["lastAction"] = RotateRight
    .metadata["lastActionSuccess"] = True
    .metadata["errorMessage"] = "
    .metadata["actionReturn"] = None
> dict_keys(['objects', 'isSceneAtRest', 'agent', 'hand', 'arm', 'fov', 'cameraPosition', 'cameraOrthSize', 'thirdPartyCameras', 'collided', 'collidedObjects', 'inventoryObjects', 'sceneName', 'lastAction', 'errorMessage', 'errorCode', 'lastActionSuccess', 'screenWidth', 'screenHeight', 'agentId', 'colors', 'colorBounds', 'flatSurfacesOnGrid', 'distances', 'normals', 'isOpenableGrid', 'segmentedObjectIds', 'objectIdsInBox', 'actionIntReturn', 'actionFloatReturn', 'actionStringsReturn', 'actionFloatsReturn', 'actionVector3sReturn', 'visibleRange', 'currentTime', 'sceneBounds', 'updateCount', 'fixedUpdateCount', 'actionReturn'])
```

**the exmaple_agent.py of the ai2thor-docker**
```
(alfred_env) maguro@s184:~/projects/ai2thor-docker$ python example_agent.py 
Skipping Xorg server - DISPLAY is already running at :1
{'cameraHorizon': 0.0,
 'inHighFrictionArea': False,
 'isStanding': True,
 'name': 'agent',
 'position': {'x': -1.5, 'y': 0.9009982347488403, 'z': -1.5},
 'rotation': {'x': -0.0, 'y': 270.0, 'z': 0.0}}
```

Additionally, I tried changing tempfile function in [the `fifo_server.py` of  the ai2thor](https://github.com/allenai/ai2thor/blob/main/ai2thor/fifo_server.py#L54)
The changed lines as follows,
```
54 - self.tmp_dir = tempfile.TemporaryDirectory()
55 - self.server_pipe_path = os.path.join(self.tmp_dir.name, "server.pipe")
56 - self.client_pipe_path = os.path.join(self.tmp_dir.name, "client.pipe")

54 + self.tmp_dir = tempfile.mkdtemp()
55 + self.server_pipe_path = os.path.join(self.tmp_dir, "server.pipe")
56 + self.client_pipe_path = os.path.join(self.tmp_dir, "client.pipe")
```

However, I couldn't fix the FileExistError.
Next, I tried to changing the start function in [the `fifo_server.py` of  the ai2thor](https://github.com/allenai/ai2thor/blob/main/ai2thor/fifo_server.py#L201-L204)
```
201 -     def start(self):
202 -        os.mkfifo(self.server_pipe_path)
203 -        os.mkfifo(self.client_pipe_path)
204 -        self.started = True

201 +    def start(self):
202 +        if os.path.exists(self.server_pipe_path) or os.path.exists(self.client_pipe_path):
203 +            self.tmp_dir = tempfile.TemporaryDirectory()
204 +            self.server_pipe_path = os.path.join(self.tmp_dir.name, "server.pipe")
205 +            self.client_pipe_path = os.path.join(self.tmp_dir.name, "client.pipe")
206 +        os.mkfifo(self.server_pipe_path)
207 +        os.mkfifo(self.client_pipe_path)
208 +        self.started = True
```

However, I met another error.
```
(alfred_env) maguro@s184:~/alfred$ python check_thor.py 
/home/maguro/alfred_env/lib/python3.6/site-packages/ai2thor/controller.py:1198: UserWarning: start method depreciated. The server started when the Controller was initialized.
  "start method depreciated. The server started when the Controller was initialized."
Traceback (most recent call last):
  File "check_thor.py", line 4, in <module>
    c.start()
  File "/home/maguro/alfred_env/lib/python3.6/site-packages/ai2thor/controller.py", line 1220, in start
    self.last_event = self.server.receive()
  File "/home/maguro/alfred_env/lib/python3.6/site-packages/ai2thor/fifo_server.py", line 179, in receive
    metadata, files = self._recv_message()
  File "/home/maguro/alfred_env/lib/python3.6/site-packages/ai2thor/fifo_server.py", line 108, in _recv_message
    header = self.server_pipe.read(self.header_size)  # message type + length
ValueError: read of closed file
```

How do I fix the FileExistsError?
Please lend me your hand.

**Comment by maguro27** [comment]
It's an easy solution.
[Line 4 of `check_thor.py` of the ALFRED repository](https://github.com/askforalfred/alfred/blob/master/scripts/check_thor.py#L4) doesn't need.
The solution is as follows,

```
4 - c.start()
```
