### ISSUE TITLE
The version 2.1.0 and 0.0.34 of ai2thor incur the ConnectionResetError.

### ISSUE THREAD

**Issue by maguro27** [allenai/ai2thor#809]
I met the ConnetionResetError when I started `the controller function` after running the docker container based on slightly modified [Dockerfile](https://github.com/allenai/ai2thor-docker/blob/main/Dockerfile).
The main modification of the Dockerfile is that I change the docker image from `nvidia/cuda:$CUDA_VERSION-devel-ubuntu18.04` to `nvcr.io/nvidia/cudagl:11.1.1-devel-ubuntu18.04` because my GPU machine does not match the NVIDIA driver version (namely, use cuda 11.1 because of using NVIDIA RTX A6000)
Moreover, I downgrade the ai2thor from ver. 3.3.2 to ver. 2.1.0 or 3.3.2 to 0.0.34 because I want to use [ALFRED](https://github.com/askforalfred/alfred) and [IQA](https://github.com/danielgordon10/thor-iqa-cvpr-2018) respectively.
The full error message is as follows,

```
root@s184:/app# python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ai2thor.controller import Controller
>>> c = Controller()
>>> c.start()
thor-201909061227-Linux64: [||||||||||||||||||||||||||||||||||||||||||   98% 156.9 KiB/s]  of 390.MBTraceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.6/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 858, in start
    self.download_binary()
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 789, in download_binary
    sha256_build)
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/downloader.py", line 46, in download
    for buf in r.iter_content(1024):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

Although I inserted `time.sleep(0.01)` before [downloader.py in line 18](https://github.com/allenai/ai2thor/blob/main/ai2thor/downloader.py#L18), I cannot resolve this error.
How do I fix it?

Note that, I did not meet any error when I use ai2thor=3.3.2.
Please lend me your hands.

**Comment by maguro27** [comment]
I couldn't find the cause of the ConnectionResetError.
However, I found another solution.

1. download the ai2thor environment files directly from `http://s3-us-west-2.amazonaws.com/ai2-thor/builds/thor-201909061227-Linux64.zip` (This zip file is the ai2thor environment of `ai2thor==2.1.0`. So, please change your desired version.)
2. unzip the ai2thor environment files.
3. move the unzipped files to `~/.ai2thor/release/`.

I tried running the check script of [the ALFRED repository](https://github.com/askforalfred/alfred/blob/master/scripts/check_thor.py).
Although I get another error/warning, this error/warning can be ignored.
```
(alfred_env) maguro@s184:~$ python alfred/check_thor.py 
Found path: /home/maguro/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/home/maguro/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/home/maguro/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Unable to preload the following plugins:
	ScreenSelector.so
Display 0 'VGA-1': 1024x768 (primary device).
Logging to /home/maguro/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
(300, 300, 3)
Everything works!!!
```
