### ISSUE TITLE
Intermittent BrokenPipe

### ISSUE THREAD

**Issue by SamNPowers** [allenai/ai2thor#827]
Hi,

I'm getting this error:

```
Traceback (most recent call last):
  File "/home/snpowers/Git/continual-reinforcement-learning/continual_rl/envs/thor/thor_general_env.py", line 135, in try_step
    event = controller.step(**thor_action_data)
  File "/home/snpowers/miniconda3/envs/venv_continual_jan2021_manual/lib/python3.8/site-packages/ai2thor/controller.py", line 916, in
step
    self.server.send(action)
  File "/home/snpowers/miniconda3/envs/venv_continual_jan2021_manual/lib/python3.8/site-packages/ai2thor/fifo_server.py", line 196, in
 send
    self._send_message(
  File "/home/snpowers/miniconda3/envs/venv_continual_jan2021_manual/lib/python3.8/site-packages/ai2thor/fifo_server.py", line 175, in
 _send_message
    self.client_pipe.flush()
BrokenPipeError: [Errno 32] Broken pipe
ERROR:/glusterfs/snpowers/thor_logs/thor_main_logs/thor_2021-07-23 03:20:14.973923.log:Stepping environment with action {'action': 'Pass'} failed with exception: [Errno 32] Broken pipe.
```

randomly (generally after about 3 hours of running or so). The Player.log contains no error info to speak of (happy to post if desired). Any idea what might be happening to the Thor process to cause it to fail in this way? Or where a more helpful error message might be located? I would have assumed that generally, any failed actions would have 'lastActionSuccess' as False, with something populating the "errorMessage", instead of this rather catastrophic crash. The action that was taken immediately prior to the start of the BrokenPipe messages was a simple "MoveAhead" action that seemed to succeed.

I'm on a build that was sent to me to test out the CloudRendering pipeline. It has generally been working, but this is causing some problems.

Thanks!

**Comment by ekolve** [comment]
How many thor processes are you running?  Do you have any idea whether the GPU(s) ran out of memory?  Would it be possible to record the steps taken and replay them outside a training run to see if thor still crashes?

**Comment by SamNPowers** [comment]
Only 2 Thor processes. The GPU is currently about 1/3 used, so didn't run out of memory. (One Thor process is actually being used for training, and the other is periodically set to the state of the first using object poses, then tweaked to form a "goal image", just for context about how I'm using these.)

I am recording the steps, but not in a way that's particularly consistent with convenient playback. It's not hard to make the change to make it playbackable though, so I can do that and see if it's reproducible. I'll get back on this one.

This was the installation command:
pip install --extra-index-url https://ai2thor-pypi.allenai.org ai2thor==0+6e951f41106a17a3ec00fd43aeecf70b1c150774

I cannot readily run the non-cloudrendering version on this machine, since there is no x-server. 

I stupidly didn't save off the Player.log from any of the previous runs (by the way it seems like by default unity uses the same log file location for everything, but it can be changed via unity command line - is this exposed by Thor in any way? It would be convenient if the player log files didn't overwrite each other). So I ran it again until it died again, but this time looks a bit different.

This time player.log has several logs that I don't recall seeing on the previous runs, like:
```
Lettuce_b97186e2 cannot be placed in Floor_cc38bd03
UnityStandardAssets.Characters.FirstPerson.PhysicsRemoteFPSAgentController:placeHeldObject(SimObjPhysics, Boolean, Boolean, Int32, Si\
ngle, Boolean, RaycastHit)
UnityStandardAssets.Characters.FirstPerson.PhysicsRemoteFPSAgentController:PlaceHeldObject(String, Single, Boolean, Boolean, Int32)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
UnityStandardAssets.Characters.FirstPerson.BaseFPSAgentController:ProcessControlCommand(DynamicServerAction, Object)
<EmitFrame>d__87:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```
I guess this isn't causing the process to die, because it's being logged many times (also a few variants, with different objects and receptacles). But also I'm not sure why the lettuce can't be dropped on the floor?

The last action taken before the environment failed this most recent time was "{'action': 'GetInteractablePoses', 'objectId': 'Pan|+01.10|+00.91|-02.48', 'horizons': [0.0], 'standings': [True]}". 

The full Player.log is attached.

**Comment by ekolve** [comment]
Could you try this version?
```
pip install --extra-index-url https://ai2thor-pypi.allenai.org ai2thor==0+91139c909576f3bf95a187c5b02c6fd455d06b48
```

I don't expect this to resolve your issue, but it has some improvements to performance and also respects CUDA_VISIBLE_DEVICES when deciding which GPU to target.

**Comment by ekolve** [comment]
Is it possible for you to reproduce this with just a single instance of thor? would it be possible for you to share your code (through email is fine) that triggers the failure?  What OS is this running on?

**Comment by SamNPowers** [comment]
Sent code via email. The base operating system is CentOS, but since we can't install vulkan on the cluster machines directly, we're using a singularity instance based on Ubuntu 20 with vulkan installed. 

I will run with no goal image generation (so only the main controller) and get back to you. Running with the new installation sha in progress.

**Comment by qazwini** [comment]
I need to run a bunch of Thor processes, but it hangs. Is there a way around this?

**Comment by laurimi** [comment]
FWIW, I was encountering `BrokenPipeError: [Errno 32] Broken pipe` while calling `Controller.reset(scene)`. This was in a context with about 20 AI2THOR processes running to produce RL training samples. Problems occurred most often with `FloorPlan206`, but might also have occurred with other scenes. The first thing that happens is that Unity crashed, and after that I was starting to get the broken pipe error from attempts to communicate with the (now dead) Unity process.
Pending a fix or an analysis of what exactly is causing this, I suggest to guard calls to `Controller.reset()` like such, since the crash throws a `UnityCrashException`:
```
try:
    controller.reset()
except UnityCrashException:
    # handle the crash, e.g. restart controller to start Unity again and restart simulation
```

**Comment by qazwini** [comment]
@laurimi What exactly are you doing to restart the controller when Unity crashes?

**Comment by laurimi** [comment]
@qazwini I just re-initialize the controller object by calling the constructor/init method, since I'm not sure if it is possible to do it otherwise. I have to set again all the controller options, but this is not an issues usually since the crashes happen for me at reset when I am setting everything up anyway.
