### ISSUE TITLE
could you tell me how to deal with this problem

### ISSUE THREAD

**Issue by Yi-Zhang-git** [allenai/ai2thor#882]
Traceback (most recent call last):
  File "explorer.py", line 54, in <module>
    Explorer(**args).show()
  File "explorer.py", line 14, in __init__
    self.env.reset()
  File "/home/zy/reproduce/visual-navigation-agent-pytorch-master_2/agent/environment/thor.py", line 23, in reset
    self._initialize()
  File "/home/zy/reproduce/visual-navigation-agent-pytorch-master_2/agent/environment/thor.py", line 16, in _initialize
    self.controller.start()
  File "/home/zy/anaconda3/envs/yourEnv/lib/python3.7/site-packages/ai2thor/controller.py", line 1226, in start
    self.server.start()
  File "/home/zy/anaconda3/envs/yourEnv/lib/python3.7/site-packages/ai2thor/fifo_server.py", line 202, in start
    os.mkfifo(self.server_pipe_path)
FileExistsError: [Errno 17] File exists

**Comment by mattdeitke** [comment]
Hi @Yi-Zhang-git, mind providing a bit more code? I'm not sure what `explorer.py` or `thor.py` refers to :)

**Comment by Yi-Zhang-git** [comment]
Nowadays，i am reading paper that **Target-driven Visual Navigation in Indoor Scenes using Deep Reinforcement Learning** and studying [https://github.com/jkulhanek/visual-navigation-agent-pytorch].  When I run explorer.py this problem occurs. Thanks!!
