### ISSUE TITLE
Stop the run via VNC on Ubuntu 18.04

### ISSUE THREAD

**Issue by 1625368821** [allenai/ai2thor#929]
Hello, I'm trying Ai2THOR for the first time. I installed it via pip on Ubuntu 18.04.I installed it via VNC on another server with Tesla V100 GPU.There's no output after the controller command and I'm unable to visualize the scene. Also in the locally downloaded ~/.ai2thor directory, I don't see any game environment containing the 3D scenes.
Thanks in advance!
>>> from ai2thor.controller import Controller
>>> controller = Controller(scene="FloorPlan10")
thor-Linux64-2f8dd9f95e4016db60155a0cc18b834a6339c8e1.zip: [ 100%  27.3 KiB/s]  of 481.MB
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ros/anaconda3/envs/ai/lib/python3.7/site-packages/ai2thor/controller.py", line 498, in __init__
    host=host,
  File "/home/ros/anaconda3/envs/ai/lib/python3.7/site-packages/ai2thor/controller.py", line 1295, in start
    self.last_event = self.server.receive()
  File "/home/ros/anaconda3/envs/ai/lib/python3.7/site-packages/ai2thor/fifo_server.py", line 179, in receive
    metadata, files = self._recv_message()
  File "/home/ros/anaconda3/envs/ai/lib/python3.7/site-packages/ai2thor/fifo_server.py", line 103, in _recv_message
    self.server_pipe = open(self.server_pipe_path, "rb")
KeyboardInterrupt
>>> controller = Controller(scene="FloorPlan10")

As above,download .zip and stop,try again  controller = Controller(scene="FloorPlan10") and stop again.
Thanks in advance!

**Comment by bjzhb666** [comment]
Hi, How to solve the problem？I am facing the same situation. Thanks

**Comment by ByZ0e** [comment]
Hi, How to solve the problem？I am facing the same situation. Thanks again!
